[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hloc-cli"
version = "0.2.0"
description = "A CLI for the Hierarchical-Localization package"
dependencies = ["tyro", "loguru", "hloc"]

[project.scripts]
hloc = "hloc_cli:main"
