blank_issues_enabled: false
contact_links:
  - name: Question / Help
    url: https://github.com/hummat/hloc-cli/discussions
    about: Ask questions and get help in Discussions
  - name: hloc Documentation
    url: https://github.com/cvg/Hierarchical-Localization
    about: Check the upstream hloc documentation
